services:
  db:
    image: bitnami/mariadb:latest
    container_name: latasisa_db
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - latasisa-net
    restart: always

  app:
    image: ghcr.io/itstealth/latasia:latest
    container_name: latasisa_app
    ports:
      - "127.0.0.1:8081:80"
    # THIS IS THE MAGIC FIX:
    env_file: 
      - .env
    depends_on:
      - db
    networks:
      - latasisa-net
    restart: always

networks:
  latasisa-net:
    driver: bridge